/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.3 */

#include "Pufferfish/Application/mcu_pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Range, Range, AUTO)


PB_BIND(AlarmLimits, AlarmLimits, AUTO)


PB_BIND(AlarmLimitsRequest, AlarmLimitsRequest, AUTO)


PB_BIND(SensorMeasurements, SensorMeasurements, AUTO)


PB_BIND(CycleMeasurements, CycleMeasurements, AUTO)


PB_BIND(Parameters, Parameters, AUTO)


PB_BIND(ParametersRequest, ParametersRequest, AUTO)


PB_BIND(Ping, Ping, AUTO)


PB_BIND(Announcement, Announcement, AUTO)


PB_BIND(LogEvent, LogEvent, AUTO)


PB_BIND(ExpectedLogEvent, ExpectedLogEvent, AUTO)


PB_BIND(NextLogEvents, NextLogEvents, AUTO)


PB_BIND(ActiveLogEvents, ActiveLogEvents, AUTO)


PB_BIND(BatteryPower, BatteryPower, AUTO)


PB_BIND(ScreenStatus, ScreenStatus, AUTO)


PB_BIND(AlarmMute, AlarmMute, AUTO)


PB_BIND(AlarmMuteRequest, AlarmMuteRequest, AUTO)





