# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: frontend_pb.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class RotaryEncoder(betterproto.Message):
    angle: int = betterproto.uint32_field(1)
    last_angle_change: float = betterproto.float_field(2)
    button_pressed: bool = betterproto.bool_field(3)
    last_button_down: float = betterproto.float_field(4)
    last_button_up: float = betterproto.float_field(5)
