# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: mcu_pb.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class VentilationMode(betterproto.Enum):
    pc_ac = 0
    pc_simv = 1
    vc_ac = 2
    vc_simv = 3
    psv = 4
    niv = 5
    hfnc = 6


class LogEventCode(betterproto.Enum):
    """Log Events"""

    fio2_too_low = 0
    fio2_too_high = 1
    spo2_too_low = 2
    spo2_too_high = 3
    rr_too_low = 4
    rr_too_high = 5
    battery_low = 6
    screen_locked = 7


@dataclass
class Alarms(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    alarm_one: bool = betterproto.bool_field(2)
    alarm_two: bool = betterproto.bool_field(3)


@dataclass
class AlarmLimits(betterproto.Message):
    rr_min: int = betterproto.uint32_field(1)
    rr_max: int = betterproto.uint32_field(2)
    pip_min: int = betterproto.uint32_field(3)
    pip_max: int = betterproto.uint32_field(4)
    peep_min: int = betterproto.uint32_field(5)
    peep_max: int = betterproto.uint32_field(6)
    ip_above_peep_min: int = betterproto.uint32_field(7)
    ip_above_peep_max: int = betterproto.uint32_field(8)
    insp_time_min: int = betterproto.uint32_field(9)
    insp_time_max: int = betterproto.uint32_field(10)
    fio2_min: int = betterproto.uint32_field(11)
    fio2_max: int = betterproto.uint32_field(12)
    paw_min: int = betterproto.uint32_field(13)
    paw_max: int = betterproto.uint32_field(14)
    mve_min: int = betterproto.uint32_field(15)
    mve_max: int = betterproto.uint32_field(16)
    tv_min: int = betterproto.uint32_field(17)
    tv_max: int = betterproto.uint32_field(18)
    etco2_min: int = betterproto.uint32_field(19)
    etco2_max: int = betterproto.uint32_field(20)
    flow_min: int = betterproto.uint32_field(21)
    flow_max: int = betterproto.uint32_field(22)
    apnea_min: int = betterproto.uint32_field(23)
    apnea_max: int = betterproto.uint32_field(24)
    spo2_min: int = betterproto.uint32_field(25)
    spo2_max: int = betterproto.uint32_field(26)


@dataclass
class AlarmLimitsRequest(betterproto.Message):
    rr_min: int = betterproto.uint32_field(1)
    rr_max: int = betterproto.uint32_field(2)
    pip_min: int = betterproto.uint32_field(3)
    pip_max: int = betterproto.uint32_field(4)
    peep_min: int = betterproto.uint32_field(5)
    peep_max: int = betterproto.uint32_field(6)
    ip_above_peep_min: int = betterproto.uint32_field(7)
    ip_above_peep_max: int = betterproto.uint32_field(8)
    insp_time_min: int = betterproto.uint32_field(9)
    insp_time_max: int = betterproto.uint32_field(10)
    fio2_min: int = betterproto.uint32_field(11)
    fio2_max: int = betterproto.uint32_field(12)
    paw_min: int = betterproto.uint32_field(13)
    paw_max: int = betterproto.uint32_field(14)
    mve_min: int = betterproto.uint32_field(15)
    mve_max: int = betterproto.uint32_field(16)
    tv_min: int = betterproto.uint32_field(17)
    tv_max: int = betterproto.uint32_field(18)
    etco2_min: int = betterproto.uint32_field(19)
    etco2_max: int = betterproto.uint32_field(20)
    flow_min: int = betterproto.uint32_field(21)
    flow_max: int = betterproto.uint32_field(22)
    apnea_min: int = betterproto.uint32_field(23)
    apnea_max: int = betterproto.uint32_field(24)
    spo2_min: int = betterproto.uint32_field(25)
    spo2_max: int = betterproto.uint32_field(26)


@dataclass
class SensorMeasurements(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    cycle: int = betterproto.uint32_field(2)
    paw: float = betterproto.float_field(3)
    flow: float = betterproto.float_field(4)
    volume: float = betterproto.float_field(5)
    fio2: float = betterproto.float_field(6)
    spo2: float = betterproto.float_field(7)


@dataclass
class CycleMeasurements(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    vt: float = betterproto.float_field(2)
    rr: float = betterproto.float_field(3)
    peep: float = betterproto.float_field(4)
    pip: float = betterproto.float_field(5)
    ip: float = betterproto.float_field(6)
    ve: float = betterproto.float_field(7)


@dataclass
class Parameters(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    mode: "VentilationMode" = betterproto.enum_field(2)
    pip: float = betterproto.float_field(3)
    peep: float = betterproto.float_field(4)
    vt: float = betterproto.float_field(5)
    rr: float = betterproto.float_field(6)
    ie: float = betterproto.float_field(7)
    fio2: float = betterproto.float_field(8)
    flow: float = betterproto.float_field(9)
    ventilating: bool = betterproto.bool_field(10)


@dataclass
class ParametersRequest(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    mode: "VentilationMode" = betterproto.enum_field(2)
    pip: float = betterproto.float_field(3)
    peep: float = betterproto.float_field(4)
    vt: float = betterproto.float_field(5)
    rr: float = betterproto.float_field(6)
    ie: float = betterproto.float_field(7)
    fio2: float = betterproto.float_field(8)
    flow: float = betterproto.float_field(9)
    ventilating: bool = betterproto.bool_field(10)


@dataclass
class Ping(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    id: int = betterproto.uint32_field(2)


@dataclass
class Announcement(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    announcement: bytes = betterproto.bytes_field(2)


@dataclass
class LogEvent(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    time: int = betterproto.uint32_field(2)
    code: "LogEventCode" = betterproto.enum_field(3)
    old_value: float = betterproto.float_field(4)
    new_value: float = betterproto.float_field(5)


@dataclass
class ExpectedLogEvent(betterproto.Message):
    id: int = betterproto.uint32_field(1)


@dataclass
class NextLogEvents(betterproto.Message):
    next_expected: int = betterproto.uint32_field(1)
    total: int = betterproto.uint32_field(2)
    remaining: int = betterproto.uint32_field(3)
    elements: List["LogEvent"] = betterproto.message_field(4)


@dataclass
class ActiveLogEvents(betterproto.Message):
    id: List[int] = betterproto.uint32_field(1)


@dataclass
class BatteryPower(betterproto.Message):
    power_left: int = betterproto.uint32_field(1)


@dataclass
class ScreenStatus(betterproto.Message):
    lock: bool = betterproto.bool_field(1)
