# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: mcu_pb.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class SpontaneousSupport(betterproto.Enum):
    ac = 0
    simv = 1


class VentilationCycling(betterproto.Enum):
    pc = 0
    vc = 1
    psv = 2


@dataclass
class Alarms(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    alarm_one: bool = betterproto.bool_field(2)
    alarm_two: bool = betterproto.bool_field(3)


@dataclass
class SensorMeasurements(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    paw: float = betterproto.float_field(2)
    flow: float = betterproto.float_field(3)
    volume: float = betterproto.float_field(4)
    fio2: float = betterproto.float_field(5)


@dataclass
class CycleMeasurements(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    vt: float = betterproto.float_field(2)
    rr: float = betterproto.float_field(3)
    peep: float = betterproto.float_field(4)
    pip: float = betterproto.float_field(5)
    ip: float = betterproto.float_field(6)
    ve: float = betterproto.float_field(7)


@dataclass
class VentilationMode(betterproto.Message):
    support: "SpontaneousSupport" = betterproto.enum_field(1)
    cycling: "VentilationCycling" = betterproto.enum_field(2)


@dataclass
class Parameters(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    mode: "VentilationMode" = betterproto.message_field(2)
    pip: float = betterproto.float_field(3)
    peep: float = betterproto.float_field(4)
    vt: float = betterproto.float_field(5)
    rr: float = betterproto.float_field(6)
    ie: float = betterproto.float_field(7)
    fio2: float = betterproto.float_field(8)


@dataclass
class ParametersRequest(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    mode: "VentilationMode" = betterproto.message_field(2)
    pip: float = betterproto.float_field(3)
    peep: float = betterproto.float_field(4)
    vt: float = betterproto.float_field(5)
    rr: float = betterproto.float_field(6)
    ie: float = betterproto.float_field(7)
    fio2: float = betterproto.float_field(8)


@dataclass
class Ping(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    id: int = betterproto.uint32_field(2)


@dataclass
class Announcement(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    announcement: bytes = betterproto.bytes_field(2)
