# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: mcu_pb.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class VentilationMode(betterproto.Enum):
    pc_ac = 0
    pc_simv = 1
    vc_ac = 2
    vc_simv = 3
    psv = 4
    niv = 5
    hfnc = 6


class LogEventCode(betterproto.Enum):
    """Log Events"""

    fio2_too_low = 0
    fio2_too_high = 1
    spo2_too_low = 2
    spo2_too_high = 3
    rr_too_low = 4
    rr_too_high = 5
    battery_low = 6
    screen_locked = 7


@dataclass
class Range(betterproto.Message):
    lower: int = betterproto.uint32_field(1)
    upper: int = betterproto.uint32_field(2)


@dataclass
class AlarmLimits(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    fio2: "Range" = betterproto.message_field(2)
    spo2: "Range" = betterproto.message_field(3)
    rr: "Range" = betterproto.message_field(4)
    pip: "Range" = betterproto.message_field(5)
    peep: "Range" = betterproto.message_field(6)
    ip_above_peep: "Range" = betterproto.message_field(7)
    insp_time: "Range" = betterproto.message_field(8)
    paw: "Range" = betterproto.message_field(9)
    mve: "Range" = betterproto.message_field(10)
    tv: "Range" = betterproto.message_field(11)
    etco2: "Range" = betterproto.message_field(12)
    flow: "Range" = betterproto.message_field(13)
    apnea: "Range" = betterproto.message_field(14)


@dataclass
class AlarmLimitsRequest(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    fio2: "Range" = betterproto.message_field(2)
    spo2: "Range" = betterproto.message_field(3)
    rr: "Range" = betterproto.message_field(4)
    pip: "Range" = betterproto.message_field(5)
    peep: "Range" = betterproto.message_field(6)
    ip_above_peep: "Range" = betterproto.message_field(7)
    insp_time: "Range" = betterproto.message_field(8)
    paw: "Range" = betterproto.message_field(9)
    mve: "Range" = betterproto.message_field(10)
    tv: "Range" = betterproto.message_field(11)
    etco2: "Range" = betterproto.message_field(12)
    flow: "Range" = betterproto.message_field(13)
    apnea: "Range" = betterproto.message_field(14)


@dataclass
class SensorMeasurements(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    cycle: int = betterproto.uint32_field(2)
    paw: float = betterproto.float_field(3)
    flow: float = betterproto.float_field(4)
    volume: float = betterproto.float_field(5)
    fio2: float = betterproto.float_field(6)
    spo2: float = betterproto.float_field(7)


@dataclass
class CycleMeasurements(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    vt: float = betterproto.float_field(2)
    rr: float = betterproto.float_field(3)
    peep: float = betterproto.float_field(4)
    pip: float = betterproto.float_field(5)
    ip: float = betterproto.float_field(6)
    ve: float = betterproto.float_field(7)


@dataclass
class Parameters(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    mode: "VentilationMode" = betterproto.enum_field(2)
    pip: float = betterproto.float_field(3)
    peep: float = betterproto.float_field(4)
    vt: float = betterproto.float_field(5)
    rr: float = betterproto.float_field(6)
    ie: float = betterproto.float_field(7)
    fio2: float = betterproto.float_field(8)
    flow: float = betterproto.float_field(9)
    ventilating: bool = betterproto.bool_field(10)


@dataclass
class ParametersRequest(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    mode: "VentilationMode" = betterproto.enum_field(2)
    pip: float = betterproto.float_field(3)
    peep: float = betterproto.float_field(4)
    vt: float = betterproto.float_field(5)
    rr: float = betterproto.float_field(6)
    ie: float = betterproto.float_field(7)
    fio2: float = betterproto.float_field(8)
    flow: float = betterproto.float_field(9)
    ventilating: bool = betterproto.bool_field(10)


@dataclass
class Ping(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    id: int = betterproto.uint32_field(2)


@dataclass
class Announcement(betterproto.Message):
    time: int = betterproto.uint32_field(1)
    announcement: bytes = betterproto.bytes_field(2)


@dataclass
class LogEvent(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    time: int = betterproto.uint32_field(2)
    code: "LogEventCode" = betterproto.enum_field(3)
    alarm_limits: "Range" = betterproto.message_field(4)
    old_value: float = betterproto.float_field(5)
    new_value: float = betterproto.float_field(6)


@dataclass
class ExpectedLogEvent(betterproto.Message):
    id: int = betterproto.uint32_field(1)


@dataclass
class NextLogEvents(betterproto.Message):
    next_expected: int = betterproto.uint32_field(1)
    total: int = betterproto.uint32_field(2)
    remaining: int = betterproto.uint32_field(3)
    elements: List["LogEvent"] = betterproto.message_field(4)


@dataclass
class ActiveLogEvents(betterproto.Message):
    id: List[int] = betterproto.uint32_field(1)


@dataclass
class BatteryPower(betterproto.Message):
    power_left: int = betterproto.uint32_field(1)


@dataclass
class ScreenStatus(betterproto.Message):
    lock: bool = betterproto.bool_field(1)


@dataclass
class AlarmMute(betterproto.Message):
    active: bool = betterproto.bool_field(1)
    remaining: float = betterproto.float_field(2)


@dataclass
class AlarmMuteRequest(betterproto.Message):
    active: bool = betterproto.bool_field(1)
    remaining: float = betterproto.float_field(2)
